export const data = [
  {
    '@id': 'http://bio2rdf.org/cas:120993-53-5',
    '@type': 'http://bio2rdf.org/cas_vocabulary:Resource',
    'http://purl.org/dc/terms/identifier': { '@value': 'cas:120993-53-5', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://rdfs.org/ns/void#inDataset': [{ '@id': 'http://bio2rdf.org/kegg_resource:bio2rdf.dataset.kegg.R3' },
	    { '@id': 'http://bio2rdf.org/ctd_resource:bio2rdf.dataset.ctd.R3' },
	    { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' }],
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': { '@value': '120993-53-5', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': { '@value': 'cas', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': { '@value': 'http://bio2rdf.org/cas:120993-53-5', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:x-identifiers.org': { '@id': 'http://identifiers.org/cas/120993-53-5' },
  },
  {
    '@id': 'http://bio2rdf.org/kegg_resource:bio2rdf.dataset.kegg.R3',
    '@type': 'http://purl.org/dc/terms/Dataset',
    'http://www.w3.org/ns/dcat#distribution': { '@id': 'http://download.bio2rdf.org/release/3/kegg/kegg-pathway.nq.gz' },
  },
  {
    '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3',
    '@type': 'http://purl.org/dc/terms/Dataset',
    'http://www.w3.org/ns/dcat#distribution': { '@id': 'http://download.bio2rdf.org/release/3/drugbank/drugbank.nq.gz' },
  },
  {
    '@id': 'http://bio2rdf.org/ahfs:20:12.04.12',
    '@type': 'http://bio2rdf.org/ahfs_vocabulary:Resource',
    'http://purl.org/dc/terms/identifier': { '@value': 'ahfs:20:12.04.12', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://rdfs.org/ns/void#inDataset': { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': { '@value': '20:12.04.12', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': { '@value': 'ahfs', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': { '@value': 'http://bio2rdf.org/ahfs:20:12.04.12', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
  },
  {
    '@id': 'http://bio2rdf.org/atc:B01AE02',
    '@type': 'http://bio2rdf.org/atc_vocabulary:Resource',
    'http://purl.org/dc/terms/identifier': { '@value': 'atc:B01AE02', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://rdfs.org/ns/void#inDataset': [{ '@id': 'http://bio2rdf.org/kegg_resource:bio2rdf.dataset.kegg.R3' },
	    { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' }],
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': { '@value': 'B01AE02', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': { '@value': 'atc', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': { '@value': 'http://bio2rdf.org/atc:B01AE02', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:x-identifiers.org': { '@id': 'http://identifiers.org/atc/B01AE02' },
  },
  {
    '@id': 'http://bio2rdf.org/drugbank:BE0000048',
    '@type': ['http://bio2rdf.org/drugbank_vocabulary:Target',
	    'http://bio2rdf.org/drugbank_vocabulary:Resource'],
    'http://www.w3.org/2000/01/rdf-schema#label': { '@value': 'Prothrombin [drugbank:BE0000048]', '@language': 'en' },
    'http://purl.org/dc/terms/title': { '@value': 'Prothrombin', '@language': 'en' },
    'http://purl.org/dc/terms/identifier': { '@value': 'drugbank:BE0000048', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://rdfs.org/ns/void#inDataset': { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': { '@value': 'BE0000048', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': { '@value': 'drugbank', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': { '@value': 'http://bio2rdf.org/drugbank:BE0000048', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:x-identifiers.org': { '@id': 'http://identifiers.org/drugbank/BE0000048' },
    'http://bio2rdf.org/drugbank_vocabulary:amino-acid-sequence': { '@value': '>Prothrombin precursor\nMAHVRGLQLPGCLALAALCSLVHSQHVFLAPQQARSLLQRVRRANTFLEEVRKGNLEREC\nVEETCSYEEAFEALESSTATDVFWAKYTACETARTPRDKLAACLEGNCAEGLGTNYRGHV\nNITRSGIECQLWRSRYPHKPEINSTTHPGADLQENFCRNPDSSTTGPWCYTTDPTVRRQE\nCSIPVCGQDQVTVAMTPRSEGSSVNLSPPLEQCVPDRGQQYQGRLAVTTHGLPCLAWASA\nQAKALSKHQDFNSAVQLVENFCRNPDGDEEGVWCYVAGKPGDFGYCDLNYCEEAVEEETG\nDGLDEDSDRAIEGRTATSEYQTFFNPRTFGSGEADCGLRPLFEKKSLEDKTERELLESYI\nDGRIVEGSDAEIGMSPWQVMLFRKSPQELLCGASLISDRWVLTAAHCLLYPPWDKNFTEN\nDLLVRIGKHSRTRYERNIEKISMLEKIYIHPRYNWRENLDRDIALMKLKKPVAFSDYIHP\nVCLPDRETAASLLQAGYKGRVTGWGNLKETWTANVGKGQPSVLQVVNLPIVERPVCKDST\nRIRITDNMFCAGYKPDEGKRGDACEGDSGGPFVMKSPFNNRWYQMGIVSWGEGCDRDGKY\nGFYTHVFRLKKWIQKVIDQFGE', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/drugbank_vocabulary:cellular-location': { '@value': 'Secreted protein; extracellular space', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/drugbank_vocabulary:gene-name': { '@value': 'F2', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/drugbank_vocabulary:gene-sequence': { '@value': '>1869 bp\nATGGCGCACGTCCGAGGCTTGCAGCTGCCTGGCTGCCTGGCCCTGGCTGCCCTGTGTAGC\nCTTGTGCACAGCCAGCATGTGTTCCTGGCTCCTCAGCAAGCACGGTCGCTGCTCCAGCGG\nGTCCGGCGAGCCAACACCTTCTTGGAGGAGGTGCGCAAGGGCAACCTAGAGCGAGAGTGC\nGTGGAGGAGACGTGCAGCTACGAGGAGGCCTTCGAGGCTCTGGAGTCCTCCACGGCTACG\nGATGTGTTCTGGGCCAAGTACACAGCTTGTGAGACAGCGAGGACGCCTCGAGATAAGCTT\nGCTGCATGTCTGGAAGGTAACTGTGCTGAGGGTCTGGGTACGAACTACCGAGGGCATGTG\nAACATCACCCGGTCAGGCATTGAGTGCCAGCTATGGAGGAGTCGCTACCCACATAAGCCT\nGAAATCAACTCCACTACCCATCCTGGGGCCGACCTACAGGAGAATTTCTGCCGCAACCCC\nGACAGCAGCACCACGGGACCCTGGTGCTACACTACAGACCCCACCGTGAGGAGGCAGGAA\nTGCAGCATCCCTGTCTGTGGCCAGGATCAAGTCACTGTAGCGATGACTCCACGCTCCGAA\nGGCTCCAGTGTGAATCTGTCACCTCCATTGGAGCAGTGTGTCCCTGATCGGGGGCAGCAG\nTACCAGGGGCGCCTGGCGGTGACCACACATGGGCTCCCCTGCCTGGCCTGGGCCAGCGCA\nCAGGCCAAGGCCCTGAGCAAGCACCAGGACTTCAACTCAGCTGTGCAGCTGGTGGAGAAC\nTTCTGCCGCAACCCAGACGGGGATGAGGAGGGCGTGTGGTGCTATGTGGCCGGGAAGCCT\nGGCGACTTTGGGTACTGCGACCTCAACTATTGTGAGGAGGCCGTGGAGGAGGAGACAGGA\nGATGGGCTGGATGAGGACTCAGACAGGGCCATCGAAGGGCGTACCGCCACCAGTGAGTAC\nCAGACTTTCTTCAATCCGAGGACCTTTGGCTCGGGAGAGGCAGACTGTGGGCTGCGACCT\nCTGTTCGAGAAGAAGTCGCTGGAGGACAAAACCGAAAGAGAGCTCCTGGAATCCTACATC\nGACGGGCGCATTGTGGAGGGCTCGGATGCAGAGATCGGCATGTCACCTTGGCAGGTGATG\nCTTTTCCGGAAGAGTCCCCAGGAGCTGCTGTGTGGGGCCAGCCTCATCAGTGACCGCTGG\nGTCCTCACCGCCGCCCACTGCCTCCTGTACCCGCCCTGGGACAAGAACTTCACCGAGAAT\nGACCTTCTGGTGCGCATTGGCAAGCACTCCCGCACAAGGTACGAGCGAAACATTGAAAAG\nATATCCATGTTGGAAAAGATCTACATCCACCCCAGGTACAACTGGCGGGAGAACCTGGAC\nCGGGACATTGCCCTGATGAAGCTGAAGAAGCCTGTTGCCTTCAGTGACTACATTCACCCT\nGTGTGTCTGCCCGACAGGGAGACGGCAGCCAGCTTGCTCCAGGCTGGATACAAGGGGCGG\nGTGACAGGCTGGGGCAACCTGAAGGAGACGTGGACAGCCAACGTTGGTAAGGGGCAGCCC\nAGTGTCCTGCAGGTGGTGAACCTGCCCATTGTGGAGCGGCCGGTCTGCAAGGACTCCACC\nCGGATCCGCATCACTGACAACATGTTCTGTGCTGGTTACAAGCCTGATGAAGGGAAACGA\nGGGGATGCCTGTGAAGGTGACAGTGGGGGACCCTTTGTCATGAAGAGCCCCTTTAACAAC\nCGCTGGTATCAAATGGGCATCGTCTCATGGGGTGAAGGCTGTGACCGGGATGGGAAATAT\nGGCTTCTACACACATGTGTTCCGCCTGAAGAAGTGGATACAGAAGGTCATTGATCAGTTT\nGGAGAGTAG', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/drugbank_vocabulary:general-function': { '@value': 'Involved in blood clotting cascade', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/drugbank_vocabulary:go-component': { '@value': 'extracellular region', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/drugbank_vocabulary:go-function': [{ '@value': 'hydrolase activity', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
	    { '@value': 'calcium ion binding', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
	    { '@value': 'catalytic activity', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
	    { '@value': 'endopeptidase activity', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
	    { '@value': 'thrombin activity', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
	    { '@value': 'binding', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
	    { '@value': 'peptidase activity', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
	    { '@value': 'cation binding', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
	    { '@value': 'ion binding', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
	    { '@value': 'serine-type endopeptidase activity', '@type': 'http://www.w3.org/2001/XMLSchema#string' }],
    'http://bio2rdf.org/drugbank_vocabulary:go-process': [{ '@value': 'macromolecule metabolism', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
	    { '@value': 'metabolism', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
	    { '@value': 'cellular protein metabolism', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
	    { '@value': 'protein metabolism', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
	    { '@value': 'regulation of body fluids', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
	    { '@value': 'proteolysis', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
	    { '@value': 'physiological process', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
	    { '@value': 'hemostasis', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
	    { '@value': 'organismal physiological process', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
	    { '@value': 'blood coagulation', '@type': 'http://www.w3.org/2001/XMLSchema#string' }],
    'http://bio2rdf.org/drugbank_vocabulary:locus': { '@value': '11p11-q12', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/drugbank_vocabulary:molecular-weight': 70037,
    'http://bio2rdf.org/drugbank_vocabulary:name': { '@value': 'Prothrombin', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/drugbank_vocabulary:organism': { '@value': 'Human', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/drugbank_vocabulary:specific-function': { '@value': 'Thrombin, which cleaves bonds after Arg and Lys, converts fibrinogen to fibrin and activates factors V, VII, VIII, XIII, and, in complex with thrombomodulin, protein C', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/drugbank_vocabulary:synonym': [{ '@value': 'Activated Factor II [IIa]', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
	    { '@value': 'Thrombin', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
	    { '@value': 'Prothrombin precursor', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
	    { '@value': 'Coagulation factor II', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
	    { '@value': 'EC 3.4.21.5', '@type': 'http://www.w3.org/2001/XMLSchema#string' }],
    'http://bio2rdf.org/drugbank_vocabulary:theoretical-pi': 5.699999809265137,
    'http://bio2rdf.org/drugbank_vocabulary:transmembrane-regions': { '@value': 'None', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/drugbank_vocabulary:x-genatlas': { '@id': 'http://bio2rdf.org/genatlas:F2' },
    'http://bio2rdf.org/drugbank_vocabulary:x-genbank': { '@id': 'http://bio2rdf.org/genbank:M17262' },
    'http://bio2rdf.org/drugbank_vocabulary:x-genecards': { '@id': 'http://bio2rdf.org/genecards:F2' },
    'http://bio2rdf.org/drugbank_vocabulary:x-gi': { '@id': 'http://bio2rdf.org/gi:339641' },
    'http://bio2rdf.org/drugbank_vocabulary:x-hgnc': { '@id': 'http://bio2rdf.org/hgnc:3535' },
    'http://bio2rdf.org/drugbank_vocabulary:x-pfam': [{ '@id': 'http://bio2rdf.org/pfam:PF00051' },
	    { '@id': 'http://bio2rdf.org/pfam:PF00594' },
	    { '@id': 'http://bio2rdf.org/pfam:PF00089' }],
    'http://bio2rdf.org/drugbank_vocabulary:x-taxonomy': { '@id': 'http://bio2rdf.org/taxonomy:9606' },
    'http://bio2rdf.org/drugbank_vocabulary:x-uniprot': [{ '@id': 'http://bio2rdf.org/uniprot:THRB_HUMAN' },
	    { '@id': 'http://bio2rdf.org/uniprot:P00734' }],
  },
  {
    '@id': 'http://bio2rdf.org/drugbank:DB00001',
    '@type': ['http://bio2rdf.org/drugbank_vocabulary:Drug',
	    'http://bio2rdf.org/drugbank_vocabulary:Biotech',
	    'http://bio2rdf.org/drugbank_vocabulary:Resource'],
    'http://www.w3.org/2000/01/rdf-schema#label': { '@value': 'Lepirudin [drugbank:DB00001]', '@language': 'en' },
    'http://www.w3.org/2000/01/rdf-schema#seeAlso': [{ '@id': 'http://www.drugbank.ca/drugs/DB00001' },
	    { '@id': 'http://www.drugs.com/cdi/lepirudin.html' },
	    { '@id': 'http://www.rxlist.com/cgi/generic/lepirudin.htm' }],
    'http://www.w3.org/2002/07/owl#sameAs': { '@id': 'http://identifiers.org/drugbank/DB00001' },
    'http://purl.org/dc/terms/title': { '@value': 'Lepirudin', '@language': 'en' },
    'http://purl.org/dc/terms/description': { '@value': 'Lepirudin is identical to natural hirudin except for substitution of leucine for isoleucine at the N-terminal end of the molecule and the absence of a sulfate group on the tyrosine at position 63. It is produced via yeast cells. Bayer ceased the production of lepirudin (Refludan) effective May 31, 2012.', '@language': 'en' },
    'http://purl.org/dc/terms/identifier': { '@value': 'drugbank:DB00001', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://rdfs.org/ns/void#inDataset': [{ '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
	    { '@id': 'http://bio2rdf.org/pharmgkb_resource:bio2rdf.dataset.pharmgkb.R3' },
	    { '@id': 'http://bio2rdf.org/kegg_resource:bio2rdf.dataset.kegg.R3' }],
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': { '@value': 'DB00001', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': { '@value': 'drugbank', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': { '@value': 'http://bio2rdf.org/drugbank:DB00001', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:x-identifiers.org': { '@id': 'http://identifiers.org/drugbank/DB00001' },
    'http://bio2rdf.org/drugbank_vocabulary:absorption': { '@id': 'http://bio2rdf.org/drugbank_resource:181c7685ad205c06870782f6812f16ee' },
    'http://bio2rdf.org/drugbank_vocabulary:affected-organism': { '@id': 'http://bio2rdf.org/drugbank_vocabulary:e1e572616d493b2affcc653e19cbcd21' },
    'http://bio2rdf.org/drugbank_vocabulary:brand': [{ '@id': 'http://bio2rdf.org/drugbank_vocabulary:6e0936d286d1a49434aae69920aea8cc' },
	    { '@id': 'http://bio2rdf.org/drugbank_vocabulary:e78186eb12eeaebda8a530a67513beea' }],
    'http://bio2rdf.org/drugbank_vocabulary:category': [{ '@id': 'http://bio2rdf.org/drugbank_vocabulary:Antithrombins' },
	    { '@id': 'http://bio2rdf.org/drugbank_vocabulary:Fibrinolytic-Agents' }],
    'http://bio2rdf.org/drugbank_vocabulary:clearance': { '@id': 'http://bio2rdf.org/drugbank_resource:5fbb4f37de38dd96b4bc5a493ba80c43' },
    'http://bio2rdf.org/drugbank_vocabulary:drug-classification-category': [{ '@id': 'http://bio2rdf.org/drugbank_resource:a3f103472df033cd9cebe2cd3d070f28' },
	    { '@id': 'http://bio2rdf.org/drugbank_resource:f23a6d41e86ea34902cbd460e2aae96c' },
	    { '@id': 'http://bio2rdf.org/drugbank_resource:f950cb0e3944f0cd7a848949bf1927b9' },
	    { '@id': 'http://bio2rdf.org/drugbank_resource:1c07425599c53df55d08143b978678c3' },
	    { '@id': 'http://bio2rdf.org/drugbank_resource:d41d8cd98f00b204e9800998ecf8427e' },
	    { '@id': 'http://bio2rdf.org/drugbank_resource:e03b86188adaa1e19757016c7399f985' }],
    'http://bio2rdf.org/drugbank_vocabulary:drugbank-id': [{ '@value': 'DB00001', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
	    { '@value': 'BTD00024', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
	    { '@value': 'BIOD00024', '@type': 'http://www.w3.org/2001/XMLSchema#string' }],
    'http://bio2rdf.org/drugbank_vocabulary:experimental-properties': [{ '@id': 'http://bio2rdf.org/drugbank_resource:experimental-properties-DB00001-1' },
	    { '@id': 'http://bio2rdf.org/drugbank_resource:experimental-properties-DB00001-2' },
	    { '@id': 'http://bio2rdf.org/drugbank_resource:experimental-properties-DB00001-3' },
	    { '@id': 'http://bio2rdf.org/drugbank_resource:experimental-properties-DB00001-4' },
	    { '@id': 'http://bio2rdf.org/drugbank_resource:experimental-properties-DB00001-5' }],
    'http://bio2rdf.org/drugbank_vocabulary:group': { '@id': 'http://bio2rdf.org/drugbank_vocabulary:Approved' },
    'http://bio2rdf.org/drugbank_vocabulary:half-life': { '@id': 'http://bio2rdf.org/drugbank_resource:bac0f73968419523c559f2f304f99085' },
    'http://bio2rdf.org/drugbank_vocabulary:indication': { '@id': 'http://bio2rdf.org/drugbank_resource:2c12de5ab49848a68d96f272e45c15a5' },
    'http://bio2rdf.org/drugbank_vocabulary:manufacturer': { '@id': 'http://bio2rdf.org/drugbank_resource:e12afb0bd3360355b845f42cd59876cf' },
    'http://bio2rdf.org/drugbank_vocabulary:mechanism-of-action': { '@id': 'http://bio2rdf.org/drugbank_resource:78367877e3152b1b2a9c9c96e2630cd6' },
    'http://bio2rdf.org/drugbank_vocabulary:packager': [{ '@id': 'http://bio2rdf.org/drugbank_resource:78a5bb17aec2925c810857cbb309d563' },
	    { '@id': 'http://bio2rdf.org/drugbank_resource:baa0075ca19e190f1ade297760ab9076' }],
    'http://bio2rdf.org/drugbank_vocabulary:patent': [{ '@id': 'http://bio2rdf.org/uspto:1339104' },
	    { '@id': 'http://bio2rdf.org/uspto:5180668' }],
    'http://bio2rdf.org/drugbank_vocabulary:pharmacodynamics': { '@id': 'http://bio2rdf.org/drugbank_resource:2818d0288993e12e4ac84c4d2c786955' },
    'http://bio2rdf.org/drugbank_vocabulary:product': { '@id': 'http://bio2rdf.org/drugbank_resource:172d9ce8065ac96f019189b12bde6767' },
    'http://bio2rdf.org/drugbank_vocabulary:route-of-elimination': { '@id': 'http://bio2rdf.org/drugbank_resource:828b29bff442579f8c0b5b4bb47b0905' },
    'http://bio2rdf.org/drugbank_vocabulary:synonym': { '@id': 'http://bio2rdf.org/drugbank_vocabulary:1018a3b49ee9295273f2932677150e92' },
    'http://bio2rdf.org/drugbank_vocabulary:target': { '@id': 'http://bio2rdf.org/drugbank:BE0000048' },
    'http://bio2rdf.org/drugbank_vocabulary:toxicity': { '@id': 'http://bio2rdf.org/drugbank_resource:c8d835e69a571598174942b76bdd718b' },
    'http://bio2rdf.org/drugbank_vocabulary:volume-of-distribution': { '@id': 'http://bio2rdf.org/drugbank_resource:5bffcb7818d2066c399c8c2b365ffca0' },
    'http://bio2rdf.org/drugbank_vocabulary:x-ahfs': { '@id': 'http://bio2rdf.org/ahfs:20:12.04.12' },
    'http://bio2rdf.org/drugbank_vocabulary:x-atc': { '@id': 'http://bio2rdf.org/atc:B01AE02' },
    'http://bio2rdf.org/drugbank_vocabulary:x-cas': { '@id': 'http://bio2rdf.org/cas:120993-53-5' },
    'http://bio2rdf.org/drugbank_vocabulary:x-kegg': { '@id': 'http://bio2rdf.org/kegg:D06880' },
    'http://bio2rdf.org/drugbank_vocabulary:x-ndc': { '@id': 'http://bio2rdf.org/ndc:50419-150-57' },
    'http://bio2rdf.org/drugbank_vocabulary:x-pharmgkb': { '@id': 'http://bio2rdf.org/pharmgkb:PA450195' },
    'http://bio2rdf.org/drugbank_vocabulary:x-uniprot': { '@id': 'http://bio2rdf.org/uniprot:P01050' },
    'http://bio2rdf.org/drugbank_vocabulary:x-wikipedia': { '@id': 'http://bio2rdf.org/wikipedia:Lepirudin' },
  },
  {
    '@id': 'http://bio2rdf.org/drugbank_resource:172d9ce8065ac96f019189b12bde6767',
    '@type': ['http://bio2rdf.org/drugbank_vocabulary:Pharmaceutical',
	    'http://bio2rdf.org/drugbank_vocabulary:Resource'],
    'http://www.w3.org/2000/01/rdf-schema#label': { '@value': 'Refludan 50 mg vial [drugbank_resource:172d9ce8065ac96f019189b12bde6767]', '@language': 'en' },
    'http://purl.org/dc/terms/title': { '@value': 'Refludan 50 mg vial', '@language': 'en' },
    'http://purl.org/dc/terms/identifier': { '@value': 'drugbank_resource:172d9ce8065ac96f019189b12bde6767', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://rdfs.org/ns/void#inDataset': { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': { '@value': '172d9ce8065ac96f019189b12bde6767', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': { '@value': 'drugbank_resource', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': { '@value': 'http://bio2rdf.org/drugbank_resource:172d9ce8065ac96f019189b12bde6767', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/drugbank_vocabulary:form': { '@id': 'http://bio2rdf.org/drugbank_vocabulary:808e7e17f24f9300e417160cb16993d4' },
    'http://bio2rdf.org/drugbank_vocabulary:price': 273.1900024414062,
  },
  {
    '@id': 'http://bio2rdf.org/drugbank_resource:181c7685ad205c06870782f6812f16ee',
    '@type': ['http://bio2rdf.org/drugbank_vocabulary:Absorption',
	    'http://bio2rdf.org/drugbank_vocabulary:Resource'],
    'http://www.w3.org/2000/01/rdf-schema#label': { '@value': 'absorption for drugbank:DB00001 [drugbank_resource:181c7685ad205c06870782f6812f16ee]', '@language': 'en' },
    'http://purl.org/dc/terms/title': { '@value': 'absorption for drugbank:DB00001', '@language': 'en' },
    'http://purl.org/dc/terms/description': { '@value': 'Bioavailability is 100% following injection.', '@language': 'en' },
    'http://purl.org/dc/terms/identifier': { '@value': 'drugbank_resource:181c7685ad205c06870782f6812f16ee', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://rdfs.org/ns/void#inDataset': { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': { '@value': '181c7685ad205c06870782f6812f16ee', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': { '@value': 'drugbank_resource', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': { '@value': 'http://bio2rdf.org/drugbank_resource:181c7685ad205c06870782f6812f16ee', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
  },
  {
    '@id': 'http://bio2rdf.org/drugbank_resource:1c07425599c53df55d08143b978678c3',
    '@type': ['http://bio2rdf.org/drugbank_vocabulary:Drug-Classification-Category',
	    'http://bio2rdf.org/drugbank_vocabulary:Resource'],
    'http://www.w3.org/2000/01/rdf-schema#label': { '@value': 'Peptides [drugbank_resource:1c07425599c53df55d08143b978678c3]', '@language': 'en' },
    'http://purl.org/dc/terms/title': { '@value': 'Peptides', '@language': 'en' },
    'http://purl.org/dc/terms/identifier': { '@value': 'drugbank_resource:1c07425599c53df55d08143b978678c3', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://rdfs.org/ns/void#inDataset': { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': { '@value': '1c07425599c53df55d08143b978678c3', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': { '@value': 'drugbank_resource', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': { '@value': 'http://bio2rdf.org/drugbank_resource:1c07425599c53df55d08143b978678c3', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
  },
  {
    '@id': 'http://bio2rdf.org/drugbank_resource:2818d0288993e12e4ac84c4d2c786955',
    '@type': ['http://bio2rdf.org/drugbank_vocabulary:Resource',
	    'http://bio2rdf.org/drugbank_vocabulary:Pharmacodynamics'],
    'http://www.w3.org/2000/01/rdf-schema#label': { '@value': 'pharmacodynamics for drugbank:DB00001 [drugbank_resource:2818d0288993e12e4ac84c4d2c786955]', '@language': 'en' },
    'http://purl.org/dc/terms/title': { '@value': 'pharmacodynamics for drugbank:DB00001', '@language': 'en' },
    'http://purl.org/dc/terms/description': { '@value': 'Lepirudin is used to break up clots and to reduce thrombocytopenia. It binds to thrombin and prevents thrombus or clot formation. It is a highly potent, selective, and essentially irreversible inhibitor of thrombin and clot-bond thrombin. Lepirudin requires no cofactor for its anticoagulant action. Lepirudin is a recombinant form of hirudin, an endogenous anticoagulant found in medicinal leeches.', '@language': 'en' },
    'http://purl.org/dc/terms/identifier': { '@value': 'drugbank_resource:2818d0288993e12e4ac84c4d2c786955', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://rdfs.org/ns/void#inDataset': { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': { '@value': '2818d0288993e12e4ac84c4d2c786955', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': { '@value': 'drugbank_resource', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': { '@value': 'http://bio2rdf.org/drugbank_resource:2818d0288993e12e4ac84c4d2c786955', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
  },
  {
    '@id': 'http://bio2rdf.org/drugbank_resource:2c12de5ab49848a68d96f272e45c15a5',
    '@type': ['http://bio2rdf.org/drugbank_vocabulary:Indication',
	    'http://bio2rdf.org/drugbank_vocabulary:Resource'],
    'http://www.w3.org/2000/01/rdf-schema#label': { '@value': 'indication for drugbank:DB00001 [drugbank_resource:2c12de5ab49848a68d96f272e45c15a5]', '@language': 'en' },
    'http://purl.org/dc/terms/title': { '@value': 'indication for drugbank:DB00001', '@language': 'en' },
    'http://purl.org/dc/terms/description': { '@value': 'For the treatment of heparin-induced thrombocytopenia', '@language': 'en' },
    'http://purl.org/dc/terms/identifier': { '@value': 'drugbank_resource:2c12de5ab49848a68d96f272e45c15a5', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://rdfs.org/ns/void#inDataset': { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': { '@value': '2c12de5ab49848a68d96f272e45c15a5', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': { '@value': 'drugbank_resource', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': { '@value': 'http://bio2rdf.org/drugbank_resource:2c12de5ab49848a68d96f272e45c15a5', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
  },
  {
    '@id': 'http://bio2rdf.org/drugbank_resource:5bffcb7818d2066c399c8c2b365ffca0',
    '@type': ['http://bio2rdf.org/drugbank_vocabulary:Resource',
	    'http://bio2rdf.org/drugbank_vocabulary:Volume-of-distribution'],
    'http://www.w3.org/2000/01/rdf-schema#label': { '@value': 'volume-of-distribution for drugbank:DB00001 [drugbank_resource:5bffcb7818d2066c399c8c2b365ffca0]', '@language': 'en' },
    'http://purl.org/dc/terms/title': { '@value': 'volume-of-distribution for drugbank:DB00001', '@language': 'en' },
    'http://purl.org/dc/terms/description': { '@value': '* 12.2 L [Healthy young subjects (n = 18, age 18-60 years)]\r\n* 18.7 L [Healthy elderly subjects (n = 10, age 65-80 years)]\r\n* 18 L [Renally impaired patients (n = 16, creatinine clearance below 80 mL/min)]\r\n* 32.1 L [HIT patients (n = 73)]', '@language': 'en' },
    'http://purl.org/dc/terms/identifier': { '@value': 'drugbank_resource:5bffcb7818d2066c399c8c2b365ffca0', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://rdfs.org/ns/void#inDataset': { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': { '@value': '5bffcb7818d2066c399c8c2b365ffca0', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': { '@value': 'drugbank_resource', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': { '@value': 'http://bio2rdf.org/drugbank_resource:5bffcb7818d2066c399c8c2b365ffca0', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
  },
  {
    '@id': 'http://bio2rdf.org/drugbank_resource:5fbb4f37de38dd96b4bc5a493ba80c43',
    '@type': ['http://bio2rdf.org/drugbank_vocabulary:Resource',
	    'http://bio2rdf.org/drugbank_vocabulary:Clearance'],
    'http://www.w3.org/2000/01/rdf-schema#label': { '@value': 'clearance for drugbank:DB00001 [drugbank_resource:5fbb4f37de38dd96b4bc5a493ba80c43]', '@language': 'en' },
    'http://purl.org/dc/terms/title': { '@value': 'clearance for drugbank:DB00001', '@language': 'en' },
    'http://purl.org/dc/terms/description': { '@value': '* 164 ml/min [Healthy 18-60 yrs]\r\n* 139 ml/min [Healthy 65-80 yrs]\r\n* 61 ml/min [renal impaired]\r\n* 114 ml/min [HIT (Heparin-induced thrombocytopenia)]', '@language': 'en' },
    'http://purl.org/dc/terms/identifier': { '@value': 'drugbank_resource:5fbb4f37de38dd96b4bc5a493ba80c43', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://rdfs.org/ns/void#inDataset': { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': { '@value': '5fbb4f37de38dd96b4bc5a493ba80c43', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': { '@value': 'drugbank_resource', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': { '@value': 'http://bio2rdf.org/drugbank_resource:5fbb4f37de38dd96b4bc5a493ba80c43', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
  },
  {
    '@id': 'http://bio2rdf.org/drugbank_resource:78367877e3152b1b2a9c9c96e2630cd6',
    '@type': ['http://bio2rdf.org/drugbank_vocabulary:Resource',
	    'http://bio2rdf.org/drugbank_vocabulary:Mechanism-of-action'],
    'http://www.w3.org/2000/01/rdf-schema#label': { '@value': 'mechanism-of-action for drugbank:DB00001 [drugbank_resource:78367877e3152b1b2a9c9c96e2630cd6]', '@language': 'en' },
    'http://purl.org/dc/terms/title': { '@value': 'mechanism-of-action for drugbank:DB00001', '@language': 'en' },
    'http://purl.org/dc/terms/description': { '@value': 'Lepirudin forms a stable non-covalent complex with alpha-thrombin, thereby abolishing its ability to cleave fibrinogen and initiate the clotting cascade. The inhibition of thrombin prevents the blood clotting cascade.', '@language': 'en' },
    'http://purl.org/dc/terms/identifier': { '@value': 'drugbank_resource:78367877e3152b1b2a9c9c96e2630cd6', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://rdfs.org/ns/void#inDataset': { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': { '@value': '78367877e3152b1b2a9c9c96e2630cd6', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': { '@value': 'drugbank_resource', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': { '@value': 'http://bio2rdf.org/drugbank_resource:78367877e3152b1b2a9c9c96e2630cd6', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
  },
  {
    '@id': 'http://bio2rdf.org/drugbank_resource:78a5bb17aec2925c810857cbb309d563',
    '@type': 'http://bio2rdf.org/drugbank_vocabulary:Resource',
    'http://www.w3.org/2000/01/rdf-schema#label': { '@value': 'Bayer Healthcare [drugbank_resource:78a5bb17aec2925c810857cbb309d563]', '@language': 'en' },
    'http://www.w3.org/2000/01/rdf-schema#seeAlso': { '@id': 'http://www.bayerhealthcare.com' },
    'http://purl.org/dc/terms/title': { '@value': 'Bayer Healthcare', '@language': 'en' },
    'http://purl.org/dc/terms/identifier': { '@value': 'drugbank_resource:78a5bb17aec2925c810857cbb309d563', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://rdfs.org/ns/void#inDataset': { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': { '@value': '78a5bb17aec2925c810857cbb309d563', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': { '@value': 'drugbank_resource', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': { '@value': 'http://bio2rdf.org/drugbank_resource:78a5bb17aec2925c810857cbb309d563', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
  },
  {
    '@id': 'http://bio2rdf.org/drugbank_resource:828b29bff442579f8c0b5b4bb47b0905',
    '@type': ['http://bio2rdf.org/drugbank_vocabulary:Resource',
	    'http://bio2rdf.org/drugbank_vocabulary:Route-of-elimination'],
    'http://www.w3.org/2000/01/rdf-schema#label': { '@value': 'route-of-elimination for drugbank:DB00001 [drugbank_resource:828b29bff442579f8c0b5b4bb47b0905]', '@language': 'en' },
    'http://purl.org/dc/terms/title': { '@value': 'route-of-elimination for drugbank:DB00001', '@language': 'en' },
    'http://purl.org/dc/terms/description': { '@value': 'Lepirudin is thought to be metabolized by release of amino acids via catabolic hydrolysis of the parent drug. About 48% of the administration dose is excreted in the urine which consists of unchanged drug (35%) and other fragments of the parent drug.', '@language': 'en' },
    'http://purl.org/dc/terms/identifier': { '@value': 'drugbank_resource:828b29bff442579f8c0b5b4bb47b0905', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://rdfs.org/ns/void#inDataset': { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': { '@value': '828b29bff442579f8c0b5b4bb47b0905', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': { '@value': 'drugbank_resource', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': { '@value': 'http://bio2rdf.org/drugbank_resource:828b29bff442579f8c0b5b4bb47b0905', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
  },
  {
    '@id': 'http://bio2rdf.org/drugbank_resource:a3f103472df033cd9cebe2cd3d070f28',
    '@type': ['http://bio2rdf.org/drugbank_vocabulary:Drug-Classification-Category',
	    'http://bio2rdf.org/drugbank_vocabulary:Resource'],
    'http://www.w3.org/2000/01/rdf-schema#label': { '@value': 'Amino Acids, Peptides, and Analogues [drugbank_resource:a3f103472df033cd9cebe2cd3d070f28]', '@language': 'en' },
    'http://purl.org/dc/terms/title': { '@value': 'Amino Acids, Peptides, and Analogues', '@language': 'en' },
    'http://purl.org/dc/terms/identifier': { '@value': 'drugbank_resource:a3f103472df033cd9cebe2cd3d070f28', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://rdfs.org/ns/void#inDataset': { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': { '@value': 'a3f103472df033cd9cebe2cd3d070f28', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': { '@value': 'drugbank_resource', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': { '@value': 'http://bio2rdf.org/drugbank_resource:a3f103472df033cd9cebe2cd3d070f28', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
  },
  {
    '@id': 'http://bio2rdf.org/drugbank_resource:baa0075ca19e190f1ade297760ab9076',
    '@type': 'http://bio2rdf.org/drugbank_vocabulary:Resource',
    'http://www.w3.org/2000/01/rdf-schema#label': { '@value': 'Berlex Labs [drugbank_resource:baa0075ca19e190f1ade297760ab9076]', '@language': 'en' },
    'http://www.w3.org/2000/01/rdf-schema#seeAlso': { '@id': 'http://www.berlex.com' },
    'http://purl.org/dc/terms/title': { '@value': 'Berlex Labs', '@language': 'en' },
    'http://purl.org/dc/terms/identifier': { '@value': 'drugbank_resource:baa0075ca19e190f1ade297760ab9076', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://rdfs.org/ns/void#inDataset': { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': { '@value': 'baa0075ca19e190f1ade297760ab9076', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': { '@value': 'drugbank_resource', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': { '@value': 'http://bio2rdf.org/drugbank_resource:baa0075ca19e190f1ade297760ab9076', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
  },
  {
    '@id': 'http://bio2rdf.org/drugbank_resource:bac0f73968419523c559f2f304f99085',
    '@type': ['http://bio2rdf.org/drugbank_vocabulary:Resource',
	    'http://bio2rdf.org/drugbank_vocabulary:Half-life'],
    'http://www.w3.org/2000/01/rdf-schema#label': { '@value': 'half-life for drugbank:DB00001 [drugbank_resource:bac0f73968419523c559f2f304f99085]', '@language': 'en' },
    'http://purl.org/dc/terms/title': { '@value': 'half-life for drugbank:DB00001', '@language': 'en' },
    'http://purl.org/dc/terms/description': { '@value': 'Approximately 1.3 hours', '@language': 'en' },
    'http://purl.org/dc/terms/identifier': { '@value': 'drugbank_resource:bac0f73968419523c559f2f304f99085', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://rdfs.org/ns/void#inDataset': { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': { '@value': 'bac0f73968419523c559f2f304f99085', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': { '@value': 'drugbank_resource', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': { '@value': 'http://bio2rdf.org/drugbank_resource:bac0f73968419523c559f2f304f99085', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
  },
  {
    '@id': 'http://bio2rdf.org/drugbank_resource:c8d835e69a571598174942b76bdd718b',
    '@type': ['http://bio2rdf.org/drugbank_vocabulary:Resource',
	    'http://bio2rdf.org/drugbank_vocabulary:Toxicity'],
    'http://www.w3.org/2000/01/rdf-schema#label': { '@value': 'toxicity for drugbank:DB00001 [drugbank_resource:c8d835e69a571598174942b76bdd718b]', '@language': 'en' },
    'http://purl.org/dc/terms/title': { '@value': 'toxicity for drugbank:DB00001', '@language': 'en' },
    'http://purl.org/dc/terms/description': { '@value': 'In case of overdose (eg, suggested by excessively high aPTT values) the risk of bleeding is increased.', '@language': 'en' },
    'http://purl.org/dc/terms/identifier': { '@value': 'drugbank_resource:c8d835e69a571598174942b76bdd718b', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://rdfs.org/ns/void#inDataset': { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': { '@value': 'c8d835e69a571598174942b76bdd718b', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': { '@value': 'drugbank_resource', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': { '@value': 'http://bio2rdf.org/drugbank_resource:c8d835e69a571598174942b76bdd718b', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
  },
  {
    '@id': 'http://bio2rdf.org/drugbank_resource:d41d8cd98f00b204e9800998ecf8427e',
    '@type': ['http://bio2rdf.org/drugbank_vocabulary:Resource',
	    'http://bio2rdf.org/drugbank_vocabulary:Drug-Classification-Category'],
    'http://www.w3.org/2000/01/rdf-schema#label': { '@value': '[drugbank_resource:d41d8cd98f00b204e9800998ecf8427e]', '@language': 'en' },
    'http://purl.org/dc/terms/identifier': { '@value': 'drugbank_resource:d41d8cd98f00b204e9800998ecf8427e', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://rdfs.org/ns/void#inDataset': { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': { '@value': 'd41d8cd98f00b204e9800998ecf8427e', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': { '@value': 'drugbank_resource', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': { '@value': 'http://bio2rdf.org/drugbank_resource:d41d8cd98f00b204e9800998ecf8427e', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
  },
  {
    '@id': 'http://bio2rdf.org/drugbank_resource:e03b86188adaa1e19757016c7399f985',
    '@type': ['http://bio2rdf.org/drugbank_vocabulary:Drug-Classification-Category',
	    'http://bio2rdf.org/drugbank_vocabulary:Resource'],
    'http://www.w3.org/2000/01/rdf-schema#label': { '@value': 'Organic Acids [drugbank_resource:e03b86188adaa1e19757016c7399f985]', '@language': 'en' },
    'http://purl.org/dc/terms/title': { '@value': 'Organic Acids', '@language': 'en' },
    'http://purl.org/dc/terms/identifier': { '@value': 'drugbank_resource:e03b86188adaa1e19757016c7399f985', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://rdfs.org/ns/void#inDataset': { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': { '@value': 'e03b86188adaa1e19757016c7399f985', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': { '@value': 'drugbank_resource', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': { '@value': 'http://bio2rdf.org/drugbank_resource:e03b86188adaa1e19757016c7399f985', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
  },
  {
    '@id': 'http://bio2rdf.org/drugbank_resource:e12afb0bd3360355b845f42cd59876cf',
    '@type': ['http://bio2rdf.org/drugbank_vocabulary:Resource',
	    'http://bio2rdf.org/drugbank_vocabulary:Manufacturer'],
    'http://www.w3.org/2000/01/rdf-schema#label': { '@value': 'manufacturer for drugbank:DB00001 [drugbank_resource:e12afb0bd3360355b845f42cd59876cf]', '@language': 'en' },
    'http://www.w3.org/1999/02/22-rdf-syntax-ns#value': { '@value': 'Bayer healthcare pharmaceuticals inc', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://purl.org/dc/terms/title': { '@value': 'manufacturer for drugbank:DB00001', '@language': 'en' },
    'http://purl.org/dc/terms/identifier': { '@value': 'drugbank_resource:e12afb0bd3360355b845f42cd59876cf', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://rdfs.org/ns/void#inDataset': { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': { '@value': 'e12afb0bd3360355b845f42cd59876cf', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': { '@value': 'drugbank_resource', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': { '@value': 'http://bio2rdf.org/drugbank_resource:e12afb0bd3360355b845f42cd59876cf', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
  },
  {
    '@id': 'http://bio2rdf.org/drugbank_resource:experimental-properties-DB00001-1',
    '@type': ['http://bio2rdf.org/drugbank_vocabulary:Melting-Point',
	    'http://bio2rdf.org/drugbank_vocabulary:Resource'],
    'http://www.w3.org/2000/01/rdf-schema#label': { '@value': 'Melting Point: 65 \u00B0C from Otto, A. & Seckler, R. Eur. J. Biochem. 202:67-73 (1991) [drugbank_resource:experimental-properties-DB00001-1]', '@language': 'en' },
    'http://purl.org/dc/terms/title': { '@value': 'Melting Point: 65 \u00B0C from Otto, A. & Seckler, R. Eur. J. Biochem. 202:67-73 (1991)', '@language': 'en' },
    'http://purl.org/dc/terms/identifier': { '@value': 'drugbank_resource:experimental-properties-DB00001-1', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://rdfs.org/ns/void#inDataset': { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': { '@value': 'experimental-properties-DB00001-1', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': { '@value': 'drugbank_resource', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': { '@value': 'http://bio2rdf.org/drugbank_resource:experimental-properties-DB00001-1', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/drugbank_vocabulary:source': { '@id': 'http://bio2rdf.org/drugbank_resource:70862fbc2e443aaed3dab996dc461ef3' },
    'http://bio2rdf.org/drugbank_vocabulary:value': { '@value': '65 \u00B0C', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
  },
  {
    '@id': 'http://bio2rdf.org/drugbank_resource:experimental-properties-DB00001-2',
    '@type': ['http://bio2rdf.org/drugbank_vocabulary:Resource',
	    'http://bio2rdf.org/drugbank_vocabulary:Hydrophobicity'],
    'http://www.w3.org/2000/01/rdf-schema#label': { '@value': 'Hydrophobicity: -0.777 [drugbank_resource:experimental-properties-DB00001-2]', '@language': 'en' },
    'http://purl.org/dc/terms/title': { '@value': 'Hydrophobicity: -0.777', '@language': 'en' },
    'http://purl.org/dc/terms/identifier': { '@value': 'drugbank_resource:experimental-properties-DB00001-2', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://rdfs.org/ns/void#inDataset': { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': { '@value': 'experimental-properties-DB00001-2', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': { '@value': 'drugbank_resource', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': { '@value': 'http://bio2rdf.org/drugbank_resource:experimental-properties-DB00001-2', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/drugbank_vocabulary:value': { '@value': '-0.777', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
  },
  {
    '@id': 'http://bio2rdf.org/drugbank_resource:experimental-properties-DB00001-3',
    '@type': ['http://bio2rdf.org/drugbank_vocabulary:Resource',
	    'http://bio2rdf.org/drugbank_vocabulary:Isoelectric-Point'],
    'http://www.w3.org/2000/01/rdf-schema#label': { '@value': 'Isoelectric Point: 4.04 [drugbank_resource:experimental-properties-DB00001-3]', '@language': 'en' },
    'http://purl.org/dc/terms/title': { '@value': 'Isoelectric Point: 4.04', '@language': 'en' },
    'http://purl.org/dc/terms/identifier': { '@value': 'drugbank_resource:experimental-properties-DB00001-3', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://rdfs.org/ns/void#inDataset': { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': { '@value': 'experimental-properties-DB00001-3', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': { '@value': 'drugbank_resource', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': { '@value': 'http://bio2rdf.org/drugbank_resource:experimental-properties-DB00001-3', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/drugbank_vocabulary:value': 4.039999961853027,
  },
  {
    '@id': 'http://bio2rdf.org/drugbank_resource:experimental-properties-DB00001-4',
    '@type': ['http://bio2rdf.org/drugbank_vocabulary:Resource',
	    'http://bio2rdf.org/drugbank_vocabulary:Molecular-Weight'],
    'http://www.w3.org/2000/01/rdf-schema#label': { '@value': 'Molecular Weight: 6963.4250 [drugbank_resource:experimental-properties-DB00001-4]', '@language': 'en' },
    'http://purl.org/dc/terms/title': { '@value': 'Molecular Weight: 6963.4250', '@language': 'en' },
    'http://purl.org/dc/terms/identifier': { '@value': 'drugbank_resource:experimental-properties-DB00001-4', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://rdfs.org/ns/void#inDataset': { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': { '@value': 'experimental-properties-DB00001-4', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': { '@value': 'drugbank_resource', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': { '@value': 'http://bio2rdf.org/drugbank_resource:experimental-properties-DB00001-4', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/drugbank_vocabulary:value': 6963.4248046875,
  },
  {
    '@id': 'http://bio2rdf.org/drugbank_resource:experimental-properties-DB00001-5',
    '@type': ['http://bio2rdf.org/drugbank_vocabulary:Resource',
	    'http://bio2rdf.org/drugbank_vocabulary:Molecular-Formula'],
    'http://www.w3.org/2000/01/rdf-schema#label': { '@value': 'Molecular Formula: C287H440N80O110S6 [drugbank_resource:experimental-properties-DB00001-5]', '@language': 'en' },
    'http://purl.org/dc/terms/title': { '@value': 'Molecular Formula: C287H440N80O110S6', '@language': 'en' },
    'http://purl.org/dc/terms/identifier': { '@value': 'drugbank_resource:experimental-properties-DB00001-5', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://rdfs.org/ns/void#inDataset': { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': { '@value': 'experimental-properties-DB00001-5', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': { '@value': 'drugbank_resource', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': { '@value': 'http://bio2rdf.org/drugbank_resource:experimental-properties-DB00001-5', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/drugbank_vocabulary:value': { '@value': 'C287H440N80O110S6', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
  },
  {
    '@id': 'http://bio2rdf.org/drugbank_resource:f23a6d41e86ea34902cbd460e2aae96c',
    '@type': ['http://bio2rdf.org/drugbank_vocabulary:Drug-Classification-Category',
	    'http://bio2rdf.org/drugbank_vocabulary:Resource'],
    'http://www.w3.org/2000/01/rdf-schema#label': { '@value': 'Carboxylic Acids and Derivatives [drugbank_resource:f23a6d41e86ea34902cbd460e2aae96c]', '@language': 'en' },
    'http://purl.org/dc/terms/title': { '@value': 'Carboxylic Acids and Derivatives', '@language': 'en' },
    'http://purl.org/dc/terms/identifier': { '@value': 'drugbank_resource:f23a6d41e86ea34902cbd460e2aae96c', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://rdfs.org/ns/void#inDataset': { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': { '@value': 'f23a6d41e86ea34902cbd460e2aae96c', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': { '@value': 'drugbank_resource', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': { '@value': 'http://bio2rdf.org/drugbank_resource:f23a6d41e86ea34902cbd460e2aae96c', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
  },
  {
    '@id': 'http://bio2rdf.org/drugbank_resource:f950cb0e3944f0cd7a848949bf1927b9',
    '@type': ['http://bio2rdf.org/drugbank_vocabulary:Resource',
	    'http://bio2rdf.org/drugbank_vocabulary:Drug-Classification-Category'],
    'http://www.w3.org/2000/01/rdf-schema#label': { '@value': 'Organic Compounds [drugbank_resource:f950cb0e3944f0cd7a848949bf1927b9]', '@language': 'en' },
    'http://purl.org/dc/terms/title': { '@value': 'Organic Compounds', '@language': 'en' },
    'http://purl.org/dc/terms/identifier': { '@value': 'drugbank_resource:f950cb0e3944f0cd7a848949bf1927b9', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://rdfs.org/ns/void#inDataset': { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': { '@value': 'f950cb0e3944f0cd7a848949bf1927b9', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': { '@value': 'drugbank_resource', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': { '@value': 'http://bio2rdf.org/drugbank_resource:f950cb0e3944f0cd7a848949bf1927b9', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
  },
  {
    '@id': 'http://bio2rdf.org/drugbank_vocabulary:1018a3b49ee9295273f2932677150e92',
    '@type': ['http://bio2rdf.org/drugbank_vocabulary:Synonym',
	    'http://bio2rdf.org/drugbank_vocabulary:Resource'],
    'http://www.w3.org/2000/01/rdf-schema#label': { '@value': 'Hirudin variant-1 [drugbank_vocabulary:1018a3b49ee9295273f2932677150e92]', '@language': 'en' },
    'http://purl.org/dc/terms/title': { '@value': 'Hirudin variant-1', '@language': 'en' },
    'http://purl.org/dc/terms/identifier': { '@value': 'drugbank_vocabulary:1018a3b49ee9295273f2932677150e92', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://rdfs.org/ns/void#inDataset': { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': { '@value': '1018a3b49ee9295273f2932677150e92', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': { '@value': 'drugbank_vocabulary', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': { '@value': 'http://bio2rdf.org/drugbank_vocabulary:1018a3b49ee9295273f2932677150e92', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
  },
  {
    '@id': 'http://bio2rdf.org/drugbank_vocabulary:6e0936d286d1a49434aae69920aea8cc',
    '@type': ['http://bio2rdf.org/drugbank_vocabulary:Name',
	    'http://bio2rdf.org/drugbank_vocabulary:Resource'],
    'http://www.w3.org/2000/01/rdf-schema#label': { '@value': 'Refludan [drugbank_vocabulary:6e0936d286d1a49434aae69920aea8cc]', '@language': 'en' },
    'http://purl.org/dc/terms/title': { '@value': 'Refludan', '@language': 'en' },
    'http://purl.org/dc/terms/identifier': { '@value': 'drugbank_vocabulary:6e0936d286d1a49434aae69920aea8cc', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://rdfs.org/ns/void#inDataset': { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': { '@value': '6e0936d286d1a49434aae69920aea8cc', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': { '@value': 'drugbank_vocabulary', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': { '@value': 'http://bio2rdf.org/drugbank_vocabulary:6e0936d286d1a49434aae69920aea8cc', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/drugbank_vocabulary:company': { '@value': 'Berlex Labs', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/drugbank_vocabulary:name': { '@value': 'Refludan', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
  },
  {
    '@id': 'http://bio2rdf.org/drugbank_vocabulary:Antithrombins',
    '@type': ['http://bio2rdf.org/drugbank_vocabulary:Category',
	    'http://bio2rdf.org/drugbank_vocabulary:Resource'],
    'http://www.w3.org/2000/01/rdf-schema#label': { '@value': 'Antithrombins [drugbank_vocabulary:Antithrombins]', '@language': 'en' },
    'http://purl.org/dc/terms/title': { '@value': 'Antithrombins', '@language': 'en' },
    'http://purl.org/dc/terms/identifier': { '@value': 'drugbank_vocabulary:Antithrombins', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://rdfs.org/ns/void#inDataset': { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': { '@value': 'Antithrombins', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': { '@value': 'drugbank_vocabulary', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': { '@value': 'http://bio2rdf.org/drugbank_vocabulary:Antithrombins', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
  },
  {
    '@id': 'http://bio2rdf.org/drugbank_vocabulary:Approved',
    '@type': ['http://bio2rdf.org/drugbank_vocabulary:Group',
	    'http://bio2rdf.org/drugbank_vocabulary:Resource'],
    'http://www.w3.org/2000/01/rdf-schema#label': { '@value': 'approved [drugbank_vocabulary:Approved]', '@language': 'en' },
    'http://purl.org/dc/terms/title': { '@value': 'approved', '@language': 'en' },
    'http://purl.org/dc/terms/identifier': { '@value': 'drugbank_vocabulary:Approved', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://rdfs.org/ns/void#inDataset': { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': { '@value': 'Approved', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': { '@value': 'drugbank_vocabulary', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': { '@value': 'http://bio2rdf.org/drugbank_vocabulary:Approved', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
  },
  {
    '@id': 'http://bio2rdf.org/drugbank_vocabulary:Biotech',
    '@type': ['http://bio2rdf.org/drugbank_vocabulary:Resource',
	    'http://www.w3.org/2002/07/owl#Class'],
    'http://www.w3.org/2000/01/rdf-schema#label': { '@value': 'Biotech [drugbank_vocabulary:Biotech]', '@language': 'en' },
    'http://purl.org/dc/terms/title': { '@value': 'Biotech', '@language': 'en' },
    'http://purl.org/dc/terms/identifier': { '@value': 'drugbank_vocabulary:Biotech', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://rdfs.org/ns/void#inDataset': { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': { '@value': 'Biotech', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': { '@value': 'drugbank_vocabulary', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': { '@value': 'http://bio2rdf.org/drugbank_vocabulary:Biotech', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
  },
  {
    '@id': 'http://bio2rdf.org/drugbank_vocabulary:Drug',
    '@type': ['http://bio2rdf.org/drugbank_vocabulary:Resource',
	    'http://www.w3.org/2002/07/owl#Class'],
    'http://www.w3.org/2000/01/rdf-schema#label': { '@value': 'Drug [drugbank_vocabulary:Drug]', '@language': 'en' },
    'http://purl.org/dc/terms/title': { '@value': 'Drug', '@language': 'en' },
    'http://purl.org/dc/terms/identifier': { '@value': 'drugbank_vocabulary:Drug', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://rdfs.org/ns/void#inDataset': { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': { '@value': 'Drug', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': { '@value': 'drugbank_vocabulary', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': { '@value': 'http://bio2rdf.org/drugbank_vocabulary:Drug', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
  },
  {
    '@id': 'http://bio2rdf.org/drugbank_vocabulary:Fibrinolytic-Agents',
    '@type': ['http://bio2rdf.org/drugbank_vocabulary:Resource',
	    'http://bio2rdf.org/drugbank_vocabulary:Category'],
    'http://www.w3.org/2000/01/rdf-schema#label': { '@value': 'Fibrinolytic Agents [drugbank_vocabulary:Fibrinolytic-Agents]', '@language': 'en' },
    'http://purl.org/dc/terms/title': { '@value': 'Fibrinolytic Agents', '@language': 'en' },
    'http://purl.org/dc/terms/identifier': { '@value': 'drugbank_vocabulary:Fibrinolytic-Agents', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://rdfs.org/ns/void#inDataset': { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': { '@value': 'Fibrinolytic-Agents', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': { '@value': 'drugbank_vocabulary', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': { '@value': 'http://bio2rdf.org/drugbank_vocabulary:Fibrinolytic-Agents', '@type': 'http://www.w3.org/2001/XMLSchema#string' },
  },
  {
    '@id': 'http://bio2rdf.org/drugbank_vocabulary:Resource',
    '@type': ['http://www.w3.org/2002/07/owl#Class',
	    'http://www.w3.org/2000/01/rdf-schema#Resource'],
    'http://www.w3.org/2000/01/rdf-schema#label': 'drugbank resource [drugbank_vocabulary:Resource]',
    'http://semanticscience.org/resource/is-member-of': { '@id': 'http://bio2rdf.org/lsr:drugbank' },
  },
  {
    '@id': 'http://bio2rdf.org/drugbank_vocabulary:e1e572616d493b2affcc653e19cbcd21',
    '@type': ['http://bio2rdf.org/drugbank_vocabulary:Affected-organism',
	    'http://bio2rdf.org/drugbank_vocabulary:Resource'],
    'http://www.w3.org/2000/01/rdf-schema#label': 'Humans and other mammals [drugbank_vocabulary:e1e572616d493b2affcc653e19cbcd21]',
    'http://purl.org/dc/terms/title': 'Humans and other mammals',
    'http://purl.org/dc/terms/identifier': 'drugbank_vocabulary:e1e572616d493b2affcc653e19cbcd21',
    'http://rdfs.org/ns/void#inDataset': { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': 'e1e572616d493b2affcc653e19cbcd21',
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': 'drugbank_vocabulary',
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': 'http://bio2rdf.org/drugbank_vocabulary:e1e572616d493b2affcc653e19cbcd21',
  },
  {
    '@id': 'http://bio2rdf.org/drugbank_vocabulary:e78186eb12eeaebda8a530a67513beea',
    '@type': ['http://bio2rdf.org/drugbank_vocabulary:Resource',
	    'http://bio2rdf.org/drugbank_vocabulary:International-brand'],
    'http://www.w3.org/2000/01/rdf-schema#label': '[drugbank_vocabulary:e78186eb12eeaebda8a530a67513beea]',
    'http://purl.org/dc/terms/identifier': 'drugbank_vocabulary:e78186eb12eeaebda8a530a67513beea',
    'http://rdfs.org/ns/void#inDataset': { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': 'e78186eb12eeaebda8a530a67513beea',
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': 'drugbank_vocabulary',
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': 'http://bio2rdf.org/drugbank_vocabulary:e78186eb12eeaebda8a530a67513beea',
  },
  {
    '@id': 'http://bio2rdf.org/kegg:D06880',
    '@type': ['http://bio2rdf.org/kegg_vocabulary:Resource',
	    'http://bio2rdf.org/kegg_vocabulary:Drug'],
    'http://www.w3.org/2000/01/rdf-schema#label': 'Lepirudin (INN); Refludan (TN)\n [kegg:D06880]',
    'http://www.w3.org/2000/01/rdf-schema#seeAlso': { '@id': 'http://www.kegg.jp/dbget-bin/www_bget?D06880' },
    'http://purl.org/dc/terms/title': 'Lepirudin (INN); Refludan (TN)',
    'http://purl.org/dc/terms/identifier': 'kegg:D06880',
    'http://rdfs.org/ns/void#inDataset': [{ '@id': 'http://bio2rdf.org/kegg_resource:bio2rdf.dataset.kegg.R3' },
	    { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' }],
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': 'D06880',
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': 'kegg',
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': 'http://bio2rdf.org/kegg:D06880',
    'http://bio2rdf.org/kegg_vocabulary:drug-group': { '@id': 'http://bio2rdf.org/kegg:DG01511' },
    'http://bio2rdf.org/kegg_vocabulary:exact_mass': 6974.95703125,
    'http://bio2rdf.org/kegg_vocabulary:formula': 'C287H440N80O111S6',
    'http://bio2rdf.org/kegg_vocabulary:internal-id': 'dr:D06880',
    'http://bio2rdf.org/kegg_vocabulary:mol_weight': 6979.423828125,
    'http://bio2rdf.org/kegg_vocabulary:pathway': [{ '@id': 'http://bio2rdf.org/kegg:map04810' },
	    { '@id': 'http://bio2rdf.org/kegg:map04610' },
	    { '@id': 'http://bio2rdf.org/kegg:map04080' }],
    'http://bio2rdf.org/kegg_vocabulary:x-atc': { '@id': 'http://bio2rdf.org/atc:B01AE02' },
    'http://bio2rdf.org/kegg_vocabulary:x-cas': { '@id': 'http://bio2rdf.org/cas:138068-37-8' },
    'http://bio2rdf.org/kegg_vocabulary:x-pubchem.compound': { '@id': 'http://bio2rdf.org/pubchem.compound:49661780' },
    'http://bio2rdf.org/kegg_vocabulary:activity': 'Anticoagulant, thrombolytic agent',
    'http://bio2rdf.org/kegg_vocabulary:interaction': { '@id': 'http://bio2rdf.org/kegg_resource:e02fbaf3363491c703a333945f9d89a2' },
    'http://bio2rdf.org/kegg_vocabulary:str_map': { '@id': 'http://bio2rdf.org/kegg:map07049' },
    'http://bio2rdf.org/kegg_vocabulary:target': { '@id': 'http://bio2rdf.org/kegg_resource:dbc6cf16baa579e16bd09922d8a14b53' },
    'http://bio2rdf.org/kegg_vocabulary:x-drugbank': { '@id': 'http://bio2rdf.org/drugbank:DB00001' },
    'http://bio2rdf.org/kegg_vocabulary:type': 'Peptide',
  },
  {
    '@id': 'http://bio2rdf.org/ndc:50419-150-57',
    '@type': 'http://bio2rdf.org/ndc_vocabulary:Resource',
    'http://purl.org/dc/terms/identifier': 'ndc:50419-150-57',
    'http://rdfs.org/ns/void#inDataset': [{ '@id': 'http://bio2rdf.org/pharmgkb_resource:bio2rdf.dataset.pharmgkb.R3' },
	    { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' }],
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': '50419-150-57',
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': 'ndc',
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': 'http://bio2rdf.org/ndc:50419-150-57',
  },
  {
    '@id': 'http://bio2rdf.org/pharmgkb:PA450195',
    '@type': ['http://bio2rdf.org/pharmgkb_vocabulary:Drug',
	    'http://bio2rdf.org/pharmgkb_vocabulary:Resource'],
    'http://www.w3.org/2000/01/rdf-schema#label': 'lepirudin [pharmgkb:PA450195]',
    'http://purl.org/dc/terms/title': 'lepirudin',
    'http://purl.org/dc/terms/identifier': 'pharmgkb:PA450195',
    'http://rdfs.org/ns/void#inDataset': [{ '@id': 'http://bio2rdf.org/pharmgkb_resource:bio2rdf.dataset.pharmgkb.R3' },
	    { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' }],
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': 'PA450195',
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': 'pharmgkb',
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': 'http://bio2rdf.org/pharmgkb:PA450195',
    'http://bio2rdf.org/pharmgkb_vocabulary:drug_class': 'Drug',
    'http://bio2rdf.org/pharmgkb_vocabulary:generic_name': 'Hirudin variant-1',
    'http://bio2rdf.org/pharmgkb_vocabulary:trade_name': 'Refludan',
    'http://bio2rdf.org/pharmgkb_vocabulary:x-dailymed': { '@id': 'http://bio2rdf.org/dailymed:6d4819a3-b934-40a8-a967-947cc456c53c' },
    'http://bio2rdf.org/pharmgkb_vocabulary:x-dpd': { '@id': 'http://bio2rdf.org/dpd:2240996' },
    'http://bio2rdf.org/pharmgkb_vocabulary:x-drugbank': { '@id': 'http://bio2rdf.org/drugbank:DB00001' },
    'http://bio2rdf.org/pharmgkb_vocabulary:x-ndc': { '@id': 'http://bio2rdf.org/ndc:50419-150-57' },
    'http://bio2rdf.org/pharmgkb_vocabulary:x-pubchemcompound': { '@id': 'http://bio2rdf.org/pubchem.compound:16132441' },
    'http://bio2rdf.org/pharmgkb_vocabulary:x-pubchemsubstance': { '@id': 'http://bio2rdf.org/pubchem.substance:14818038' },
    'http://bio2rdf.org/pharmgkb_vocabulary:x-ttd': { '@id': 'http://bio2rdf.org/ttd:DAP000541' },
    'http://bio2rdf.org/pharmgkb_vocabulary:x-uniprot': { '@id': 'http://bio2rdf.org/uniprot:P01050' },
    'http://bio2rdf.org/pharmgkb_vocabulary:x-webresource': { '@id': 'webresource:http://en.wikipedia.org/wiki/Lepirudin' },
  },
  {
    '@id': 'http://bio2rdf.org/uniprot:P01050',
    '@type': 'http://bio2rdf.org/uniprot_vocabulary:Resource',
    'http://purl.org/dc/terms/identifier': 'uniprot:P01050',
    'http://rdfs.org/ns/void#inDataset': [{ '@id': 'http://bio2rdf.org/pharmgkb_resource:bio2rdf.dataset.pharmgkb.R3' },
	    { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' }],
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': 'P01050',
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': 'uniprot',
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': 'http://bio2rdf.org/uniprot:P01050',
    'http://bio2rdf.org/bio2rdf_vocabulary:x-identifiers.org': { '@id': 'http://identifiers.org/uniprot/P01050' },
  },
  {
    '@id': 'http://bio2rdf.org/uspto:1339104',
    '@type': ['http://bio2rdf.org/drugbank_vocabulary:Patent',
	    'http://bio2rdf.org/uspto_vocabulary:Resource'],
    'http://www.w3.org/2000/01/rdf-schema#label': 'Canada patent 1339104 [uspto:1339104]',
    'http://purl.org/dc/terms/title': 'Canada patent 1339104',
    'http://purl.org/dc/terms/identifier': 'uspto:1339104',
    'http://rdfs.org/ns/void#inDataset': { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': '1339104',
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': 'uspto',
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': 'http://bio2rdf.org/uspto:1339104',
    'http://bio2rdf.org/drugbank_vocabulary:approved': { '@value': '1997-07-29', '@type': 'http://www.w3.org/2001/XMLSchema#date' },
    'http://bio2rdf.org/drugbank_vocabulary:country': { '@id': 'http://bio2rdf.org/drugbank_resource:445d337b5cd5de476f99333df6b0c2a7' },
    'http://bio2rdf.org/drugbank_vocabulary:expires': { '@value': '2014-07-29', '@type': 'http://www.w3.org/2001/XMLSchema#date' },
  },
  {
    '@id': 'http://bio2rdf.org/uspto:5180668',
    '@type': ['http://bio2rdf.org/uspto_vocabulary:Resource',
	    'http://bio2rdf.org/drugbank_vocabulary:Patent'],
    'http://www.w3.org/2000/01/rdf-schema#label': 'United States patent 5180668 [uspto:5180668]',
    'http://purl.org/dc/terms/title': 'United States patent 5180668',
    'http://purl.org/dc/terms/identifier': 'uspto:5180668',
    'http://rdfs.org/ns/void#inDataset': { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': '5180668',
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': 'uspto',
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': 'http://bio2rdf.org/uspto:5180668',
    'http://bio2rdf.org/drugbank_vocabulary:approved': { '@value': '1993-01-19', '@type': 'http://www.w3.org/2001/XMLSchema#date' },
    'http://bio2rdf.org/drugbank_vocabulary:country': { '@id': 'http://bio2rdf.org/drugbank_resource:f253efe302d32ab264a76e0ce65be769' },
    'http://bio2rdf.org/drugbank_vocabulary:expires': { '@value': '2010-01-19', '@type': 'http://www.w3.org/2001/XMLSchema#date' },
  },
  {
    '@id': 'http://bio2rdf.org/wikipedia:Lepirudin',
    '@type': 'http://bio2rdf.org/wikipedia_vocabulary:Resource',
    'http://purl.org/dc/terms/identifier': 'wikipedia:Lepirudin',
    'http://rdfs.org/ns/void#inDataset': { '@id': 'http://bio2rdf.org/drugbank_resource:bio2rdf.dataset.drugbank.R3' },
    'http://bio2rdf.org/bio2rdf_vocabulary:identifier': 'Lepirudin',
    'http://bio2rdf.org/bio2rdf_vocabulary:namespace': 'wikipedia',
    'http://bio2rdf.org/bio2rdf_vocabulary:uri': 'http://bio2rdf.org/wikipedia:Lepirudin',
    'http://bio2rdf.org/bio2rdf_vocabulary:x-identifiers.org': { '@id': 'http://identifiers.org/wikipedia/Lepirudin' },
  },
  {
    '@id': 'http://bio2rdf.org/pharmgkb_resource:bio2rdf.dataset.pharmgkb.R3',
    '@type': 'http://purl.org/dc/terms/Dataset',
    'http://www.w3.org/ns/dcat#distribution': { '@id': 'http://download.bio2rdf.org/release/3/pharmgkb/drugs.nq.gz' },
  },
]
